[workspace]
resolver = "3"
members = ["crates/api", "crates/cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://git.perish.top/PerishLab/plang"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
plang-api = { path = "crates/api" }
plumb = { version = "0", registry = "perish", default-features = false }
